WIDTH=20
HEIGHT=20
ENTRY=2,5
#EXIT=100,100
OUTPUT_FILE=test
PERFECT=False
SEED=111
TILEMAP_WALL_SIZE=2,1
TILEMAP_CELL_SIZE=4,2
TILEMAP_FULL="{1000,1000,1000:1000,1000,1000}######"
TILEMAP_FULL="{1000,1000,1000:1000,1000,1000}######"
TILEMAP_FULL="{1000,1000,1000:1000,1000,1000}######"
TILEMAP_EMPTY="{0,0,0:0,0,0}      "
TILEMAP_EMPTY="{0,0,0:0,0,0}      "
TILEMAP_EMPTY="{0,0,0:0,0,0}      "
TILEMAP_BACKGROUND_SIZE=8,4
TILEMAP_BACKGROUND="{1000,1000,1000:0,0,0}##      "
TILEMAP_BACKGROUND="{1000,1000,1000:0,0,0}######  "
TILEMAP_BACKGROUND="{1000,1000,1000:0,0,0}    ##  "
TILEMAP_BACKGROUND="{1000,1000,1000:0,0,0}##  ##  "
#MAZE_PATTERN=" #   # "
#MAZE_PATTERN="  # #  "
#MAZE_PATTERN="   #   "
#MAZE_PATTERN="       "
#MAZE_PATTERN=" #  #  "
#MAZE_PATTERN="       "
#MAZE_PATTERN="#  #  #"
#MAZE_PATTERN=" ## ## "
MAZE_PATTERN="#######"
MAZE_PATTERN="# # # #"
MAZE_PATTERN="#  #  #"
MAZE_PATTERN="#     #"
MAZE_PATTERN="## ####"
MAZE_PATTERN="#     #"
MAZE_PATTERN="#  #  #"
MAZE_PATTERN="#######"
